
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'

export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'

export const USER_REQUEST = 'USER_REQUEST'
export const USER_FAILED = 'USER_FAILED'

export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'